# Generated by Django 3.1.4 on 2021-01-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses_table',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=50)),
                ('c_fee', models.IntegerField()),
                ('c_duration', models.CharField(max_length=50)),
            ],
        ),
    ]
