# Generated by Django 3.2.4 on 2021-06-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogInPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Please enter first name', max_length=250, unique=True)),
                ('last_name', models.CharField(blank=True, help_text='Please enter last name', max_length=250, null=True)),
                ('mobile_no', models.CharField(help_text=' Enter your mobile number', max_length=20, unique=True)),
            ],
        ),
    ]
